filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
    - module: logstash
      enabled: true
      output: 0.0.0.0:5044
      var.paths:
        - '/var/lib/containers/*/*.log'

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

output.logstash:
  hosts: ["0.0.0.0:5044"]

filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/containers/*/*.log'

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

setup.kibana.host: "http://0.0.0.0:5601"
setup.kibana.username: ${KIBANA_USERNAME}
setup.kibana.password: ${KIBANA_PASSWORD}