version: "3.8"

services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
    environment:
      NETWORK_HOST: 0.0.0.0
      network.host: 0.0.0.0
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: 'password'
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      http_cors_enabled : true
      http_cors_allow-origin: "*"
      http_cors_allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
      http_cors_allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
      http_cors_allow-credentials: true
    networks:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash
    volumes: 
      # - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports: 
      - "5044:5400"
      - "5201:5201"
      - "9600:9600"
    environment:
      network.host: 0.0.0.0
      LS_JAVA_OPTS: -Xmx256m -Xms256m
      LOGSTASH_INTERNAL_PASSWORD: 'password'
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    restart: always
    image: docker.elastic.co/kibana/kibana:8.0.0
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elasticsearch
    environment:
      discovery.type: "single-node"
      SERVER_HOST: 0.0.0.0
      KIBANA_SYSTEM_PASSWORD: password
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch
    
networks:
  elasticsearch:
    driver: bridge

volumes:
  elasticsearch: